# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: issue1_test

on:
  pull_request:
    branches: [ schTi-update-workflows ] #feature1_new_title

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ '3.x' ]
    name: Python ${{ matrix.python-version }} sample
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: '3.x' # Version range or exact version of a Python version to use, using SemVer's version range syntax
          architecture: 'x64' # optional x64 or x86. Defaults to x64 if not specified
      - run: python tests/Aufgabe1_test.py > test-output.txt
      - run: echo ::set-output name=result::$(grep "Yes" test-output.txt | wc -l)
        id: test
        shell: bash
      - name: PR Comment
        uses: mshick/add-pr-comment@v1
        with:
          message: |
            The tests were not successful. Just have a look at your changes, maybe you can find the mistake. Commit if you think you fixed it. Keep it up 🔥.
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          allow-repeats: true
        if: steps.test.outputs.result != '1'
      - run: exit 1
        if: steps.test.outputs.result != '1'
